import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NamePrompt from "@/components/NamePrompt";
import AuthAction from "@/components/AuthAction";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <header className="border-b p-4">
          <nav className="max-w-5xl mx-auto flex items-center justify-between">
            <div className="flex items-center gap-4">
              <a href="/" className="font-semibold">receiptiq</a>
              <a href="/upload" className="text-sm text-gray-600 hover:underline">Upload</a>
              <a href="/dashboard" className="text-sm text-gray-600 hover:underline">Dashboard</a>
              <a href="/receipts" className="text-sm text-gray-600 hover:underline">Receipts</a>
              <a href="/groups" className="text-sm text-gray-600 hover:underline">Groups</a>
            </div>
            <div className="flex items-center gap-4">
              <NamePrompt />
              <AuthAction />
            </div>
          </nav>
        </header>
  <main>{children}</main>
  </Providers>
      </body>
    </html>
  );
}
